steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ai-media-dashboard-backend:$COMMIT_SHA', '.' ]

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/ai-media-dashboard-backend:$COMMIT_SHA' ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ai-media-dashboard-backend
      - --image=gcr.io/$PROJECT_ID/ai-media-dashboard-backend:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      # - '--env-vars-file=env.yaml'    # Uncomment if you want to use env.yaml for secrets

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - gcr.io/$PROJECT_ID/ai-media-dashboard-backend:$COMMIT_SHA
